import { Routes } from '@angular/router';
import { Shell } from './core/layout/shell';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./features/login/login').then(m => m.Login) },
  {
    path: 'app',
    component: Shell,
    children: [
      { path: '', redirectTo: 'inicio', pathMatch: 'full' },
      { path: 'inicio', loadComponent: () => import('./features/dashboard/dashboard').then(m => m.Dashboard) },
      { path: 'dashboard', loadComponent: () => import('./features/reportes/reportes').then(m => m.Reportes) },
      { path: 'reportes', loadComponent: () => import('./features/reportes/reportes-landing').then(m => m.ReportesLanding) },
      { path: 'reportes/estadisticas', loadComponent: () => import('./features/reportes/reportes').then(m => m.Reportes) },
      { path: 'reportes/:tipo', loadComponent: () => import('./features/reportes/reporte').then(m => m.Reporte) },
      { path: 'ingresos', redirectTo: 'ingresos/expediente', pathMatch: 'full' },
      { path: 'ingresos/documento', loadComponent: () => import('./features/ingresos/wizard').then(m => m.IngresoWizard) },
      { path: 'ingresos/expediente', loadComponent: () => import('./features/ingresos/expediente').then(m => m.IngresoExpediente) },
      { path: 'bandeja', redirectTo: 'bandeja/por-resolver', pathMatch: 'full' },
      { path: 'bandeja/por-resolver', loadComponent: () => import('./features/bandeja/bandeja-detalle').then(m => m.BandejaDetalle) },
      { path: 'bandeja/mis-pendientes', data: { tipo: 'mis-pendientes' }, loadComponent: () => import('./features/bandeja/bandeja-lista').then(m => m.BandejaLista) },
      { path: 'bandeja/historial', data: { tipo: 'historial' }, loadComponent: () => import('./features/bandeja/bandeja-lista').then(m => m.BandejaLista) },
      { path: 'expedientes', loadComponent: () => import('./features/expedientes/expedientes').then(m => m.Expedientes) },
      { path: 'expedientes/:folio', loadComponent: () => import('./features/expedientes/expediente-detalle').then(m => m.ExpedienteDetalle) },
      { path: 'documentos', loadComponent: () => import('./features/documentos/documentos').then(m => m.Documentos) },
      { path: 'documentos/:nombre', loadComponent: () => import('./features/documentos/documento-detalle').then(m => m.DocumentoDetalle) },
      { path: 'firma', loadComponent: () => import('./features/firma/firma').then(m => m.Firma) },
      { path: 'tareas', loadComponent: () => import('./features/tareas/tareas').then(m => m.Tareas) },
      { path: 'oficina-partes', redirectTo: 'oficina-partes/entrante', pathMatch: 'full' },
      { path: 'oficina-partes/entrante', loadComponent: () => import('./features/oficina-partes/oficina-entrante').then(m => m.OficinaEntrante) },
      { path: 'oficina-partes/saliente', loadComponent: () => import('./features/oficina-partes/oficina-saliente').then(m => m.OficinaSaliente) },
      { path: 'oficina-partes/pre-ingreso', loadComponent: () => import('./features/oficina-partes/pre-ingreso').then(m => m.PreIngreso) },
      { path: 'oficina-partes/manual', loadComponent: () => import('./features/oficina-partes/manual').then(m => m.Manual) },
      { path: 'oficina-partes/distribuciones-rechazadas', loadComponent: () => import('./features/oficina-partes/distribuciones-rechazadas').then(m => m.DistribucionesRechazadas) },
      { path: 'oficina-partes/tareas-rechazadas', loadComponent: () => import('./features/oficina-partes/tareas-rechazadas').then(m => m.TareasRechazadas) },
      { path: 'oficina-partes/:tipo', loadComponent: () => import('./features/oficina-partes/oficina-partes').then(m => m.OficinaPartes) },
      { path: 'portal-ciudadano', loadComponent: () => import('./features/portal-ciudadano/portal-ciudadano').then(m => m.PortalCiudadano) },
      { path: 'mantenedores', redirectTo: 'mantenedores/usuarios', pathMatch: 'full' },
      { path: 'mantenedores/:tipo', loadComponent: () => import('./features/mantenedores/mantenedor-detalle').then(m => m.MantenedorDetalle) },
      { path: 'auditoria', loadComponent: () => import('./features/auditoria/auditoria').then(m => m.Auditoria) },
      { path: 'buscador', loadComponent: () => import('./features/buscador/buscador').then(m => m.Buscador) },
      { path: 'buscador/documentos', loadComponent: () => import('./features/buscador/buscador-documentos').then(m => m.BuscadorDocumentos) },
    ],
  },
  { path: '**', redirectTo: '' },
];
